<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Optinull.Bot-937e7a90-63de-4449-9c0a-f5da7696373a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Optinull.Application\Optinull.Application.csproj" />
    <ProjectReference Include="..\Optinull.Problems\Optinull.Problems.csproj" />
    <ProjectReference Include="..\Optinull.Infrastructure\Optinull.Infrastructure.csproj" />
  </ItemGroup>
</Project>
